# Generated by Django 3.1.1 on 2020-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201002_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='score',
            name='match_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
